### ISSUE TITLE
Invalid device ordinal

### ISSUE THREAD

**Issue by slavikkom** [mt2017-tartu-shared-task/nmt-system-C#3]
After running script to train model, I got an error 'invalid device ordinal'. In the script I specify -gpuid 1 (I tried also for 2, 5, 6). At nvidia-smi, all of this gpu were free.

**Comment by MaksymDel** [comment]
Please, add full script you run

**Comment by slavikkom** [comment]
#!/bin/bash

#The name of the job is test_job
#SBATCH -J rnnlm1_job

#The job requires 1 compute node
#SBATCH -N 1

#The job requires 1 task per node
#SBATCH --ntasks-per-node=1

#The maximum walltime of the job is a 8 days
#SBATCH -t 192:00:00

#SBATCH --mem=50G

#Leave this here if you need a GPU for your job
#SBATCH --partition=gpu

#SBATCH --gres=gpu:tesla:1

#The module with all the NMT / deep learning packages
module load python-2.7.13

python train.py -data /gpfs/hpchome/komisare/project/data/raw-all/rdy -save_model /gpfs/hpchome/komisare/project/models/demo-model -gpuid 2

**Comment by MaksymDel** [comment]
When you allocate gpu resources in SLURM, your framework sees only these set of resources. Since we allocate only one gpu, you can simply put **`-gpuid 0`** to use it. So just run the script with `-gpuid 0`

If you run commands without `gpuid `parameter specified, you will use OpenNMT-py in cpu mode (still on gpu), which is nonsense.

Another option would be to use interactive slurm session on gpu resource, but generally, I do not recommend to do so during this course.

@mt2017-tartu-shared-task/imperium 
@mt2017-tartu-shared-task/mali 
@mt2017-tartu-shared-task/powerrangers 
@mt2017-tartu-shared-task/quidditchchampions 
@mt2017-tartu-shared-task/researchers 
@mt2017-tartu-shared-task/toneko 
@fishel @maxdel

**Comment by MaksymDel** [comment]
Hi Viacheslav ,

did it solve your problem?

**Comment by slavikkom** [comment]
Yes, thanks. Now training is on 7th epoche, best model now is demo-model_acc_74.31_ppl_3.58_e6.pt. Can you please say whether it is extremely low accuracy now or quite normal?

**Comment by MaksymDel** [comment]
Are you training on small data? 

Rgarding model performance, just translate your (toy) test set with the current best model to see the BLEU score.

**Comment by slavikkom** [comment]
Now I am training on big data. I take current best model (after 12th epoche), get small subset of test set (of size 500) and run evaluation script, recieved 38.55 BLEU.
