### ISSUE TITLE
Clarification of task

### ISSUE THREAD

**Issue by slavikkom** [mt2017-tartu-shared-task/nmt-system-C#5]
I am not sure whether I correctly understand what should be done. As I understand, we should:
1. Download best model from remote server.
2. Translate preprocessed dev set file (in accurate folder there is file bpe.cleaned-tc-tok.et, so, we should just translate this file using best model).
3.  UNDO all preprocessing - it means, that we should just take file dev.et - no processing done in this file.
4. We take unprocessed test set file from lab1.
5. Which translation should we analyze - dev set that we just translated or translation of test set?

**Comment by MaksymDel** [comment]
1. Translate accurate dev set on the remote server (take dev.et, do all preprocessing, and translate it with your model;)
2. Undo all the preprocessing for your result file from step 1
3. Compare your result file from step 2 with the accurate dev.en (compute BLUE)
4. Undo preprocessing for test set from lab1 and compute BLEU


You should analyze accurate dev set translations

**Comment by MaksymDel** [comment]
Note, that you have to do all the preprocessing for dev.et from scratch (so ignore bpe.cleaned-tc-tok.et, and cleaned-tc-tok.et).

The reason is that for translation the same models as for training should be used (i.e. true casing and BPE models). 

Otherwise, your model will face unseen BPE parts and result in poor results.

@mt2017-tartu-shared-task/imperium
@mt2017-tartu-shared-task/mali
@mt2017-tartu-shared-task/powerrangers
@mt2017-tartu-shared-task/quidditchchampions
@mt2017-tartu-shared-task/researchers
@mt2017-tartu-shared-task/toneko
@fishel @maxdel

**Comment by slavikkom** [comment]
How to make UNDO for all preprocessing - it is not clear for me. Is there some scripts that perfom it, or bash can perform undo for some commands?

**Comment by MaksymDel** [comment]
There is a bush command for deBPE, and Moses scripts to do the rest.

You should find and use all the tools necessary yourself.
